### ISSUE TITLE
Question: why do we need to add this app to INSTALLED_APPS?

### ISSUE THREAD

**Issue by sobolevn** [DmytroLitvinov/django-http-referrer-policy#2]
Hi, @DmytroLitvinov!

I was reviewing our app today and found that I am adding `django_http_referrer_policy` to the `INSTALLED_APPS`.
That's what the docs say.

But, why?

There are no models, no extra steps. It should be just a middleware, shouldn't it?

**Comment by DmytroLitvinov** [comment]
Hi @sobolevn,

You are completely right. There is no reason for adding it into `INSTALLED_APPS`. That project was generated with [cookiecutter-djangopackage](https://github.com/pydanny/cookiecutter-djangopackage).

Wrong documentation is worse than not having docs at all I guess :dizzy_face:
I am going to refactor docs.

**Comment by sobolevn** [comment]
Would you like to do the honours? https://github.com/wemake-services/wemake-django-template/blob/master/%7B%7Bcookiecutter.project_name%7D%7D/server/settings/components/common.py#L51
