### ISSUE TITLE
REFERRER_POLICY can possibly have a default

### ISSUE THREAD

**Issue by sobolevn** [DmytroLitvinov/django-http-referrer-policy#4]
Do you think that providing a default for `REFERRER_POLICY` is reasonable? 
For example `no-referrer-when-downgrade` seems like a good candidate for a default value.

**Comment by DmytroLitvinov** [comment]
Sounds good to me.

From [MDN web docs](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Referrer-Policy):
> no-referrer-when-downgrade (default)
This is the default behavior if no policy is specified, or if the provided value is invalid.

**Comment by sobolevn** [comment]
Thanks a lot for the quick fix! 👍

**Comment by DmytroLitvinov** [comment]
The new version `1.1.0` will be released soon.
